### ISSUE TITLE
No module named 'pynvim'

### ISSUE THREAD

**Issue by itsfrank** [b0o/blender.nvim#1]
This plugin looks absolutely amazing, but I am having trouble getting set up.

I tried this both in a venv and not.

I have nightly neovim (0.10.0), and blender 4.1.1

I ran `pip install pynvim`. Running it now returns:
```
Requirement already satisfied: pynvim
```

When I use `:Blender` and select the profile I get the following:
```
Read prefs: "/Users/<me>/Library/Application Support/Blender/4.1/config/userpref.blend"
Traceback (most recent call last):
  File "/Users/<me>/.local/share/nvim/lazy/blender.nvim/launcher.py", line 17, in <module>
    import blender_nvim
  File "/Users/<me>/.local/share/nvim/lazy/blender.nvim/blender_nvim/__init__.py", line 6, in <module>
    from .load_addons import load_addons, setup_addon_links
  File "/Users/<me>/.local/share/nvim/lazy/blender.nvim/blender_nvim/load_addons.py", line 8, in <module>
    from .rpc import NvimRpc
  File "/Users/<me>/.local/share/nvim/lazy/blender.nvim/blender_nvim/rpc.py", line 7, in <module>
    import pynvim
ModuleNotFoundError: No module named 'pynvim'
```

Seems like the blender python environment does not have pynvim installed?

**Comment by itsfrank** [comment]
Ok I managed to solve this by doing the following:

1. Open the python console
2. Type the following:
    - `import pip`
    - `import site`
    - `pip.main(['install', 'pynvim', '--target', site.USER_SITE])`
    - `pip.main(['install', 'debugpy', '--target', site.USER_SITE])`

I'm not sure if there is a simpler way to get blender to use system-installed packages, but this has worked for now. I suspect it will break if I ever update blender again.

If this is the only way it would be great to have it documented in the readme

**Comment by b0o** [comment]
Hey there! Thanks for the feedback. I suspect you're the first to test this plugin on macOS. As soon as I have time, hopefully tonight or tomorrow, I will boot up my Mac and test the plugin there, and then will try to fix/document these issues.

**Comment by itsfrank** [comment]
> If I may ask, after you worked around this by installing pynvim manually, is the plugin working?

Yes, and it seems to be working really well, I only got it setup near the end of my day yesterday, but the little I was able to use it was super cool.

Will hopefully have the time to put it through it's paces this week, so far so good, really looking forward to the massively improved workflow!

**Comment by itsfrank** [comment]
Little update, worked on my add-on most of the day, phenomenal experience :D

**Comment by b0o** [comment]
I pushed some changes that should fix both of your issues:

- b9aecfe: if `VIRTUAL_ENV` is set, launcher.py will now add the venv's site-packages directory to the python path. Note: you need to make sure that the venv is using the same version of python as Blender is using or it will not find the site-packages directory. 
- 06aca3b: auto-detect Blender executables at common paths

It would be helpful if you try removing your workarounds and seeing if it works out of the box now. Thanks!

**Comment by itsfrank** [comment]
Thank you for the fix, unfortunately my work has pulled me off of blender plugin development for the moment, but when I get to jump back into it I will try these out!

**Comment by b0o** [comment]
No problem. I’m going to close these for now, please re-open if they’re still an issue.
